services:

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - path: ./.env
        required: true
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp-volume:/var/www/html
    ports:
      - "8080:8080" # probably also don't publish this
    networks:
      - inception
    pull_policy: never
    restart: unless-stopped

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - path: ./.env
        required: true
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306" # testing, remove later, services will connect via network
    networks:
      - inception
    pull_policy: never
    restart: unless-stopped

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vsanin/data/db-volume
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vsanin/data/wp-volume

networks:
  inception:
    name: inception
    driver: bridge